
version: '3.8'

services:
  pg-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: cocos
      POSTGRES_PASSWORD: cocospass
      POSTGRES_DB: cocosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  postgres-data: